version: "3.3"

services:
 angular_app:
  build:
   context: .
   dockerfile: ./AngularApp/Dockerfile
  container_name: AngularApp_3
  volumes:
   - angular:/usr/src/AngularApp
  networks:
  - local-network
 node_app:
  build:
   context: .
   dockerfile: ./NodeTSApp/Dockerfile
  ports:
   - "0.0.0.0:8001:8001"
  container_name: NodeApp_3
  volumes:
   - type: volume
     source: angular
     target: /usr/src/AngularApp
     volume:
      nocopy: true
  networks:
  - local-network
  depends_on:
    - mongo
    - angular_app
 mongo:
  image: mongo:latest
  container_name: AppMongo_3
  volumes:
   - ./mongo_data:/data/db
  networks:
  - local-network
  ports:
   - "27017:27017"
networks:
 local-network:
  driver: bridge
volumes:
 angular:
